### ISSUE TITLE
How to merge more than 2 data structures (tables)?

### ISSUE THREAD

**Issue by kisanme** [mtraynham/lodash-joins#14]
Say we want to join 3 data structures as we do in a database joining 3 tables with a single base table. Can we do that with this library? if so how do we go about it in code?

**Comment by mtraynham** [comment]
Hi @kisanme , sorry I've been quite absent and hope you found a solution to your issue.

If not, it's likely you can just invoke one join on 2 "tables" and then a second join on the result of the first and your third "table".

```javascript
const a = [...];
const b = [...];
const c = [...];
const r1 = _.hashLeftOuterJoin(a, ({id}) => id, b, ({id}) => id);
const r2 = _.hashLeftOuterJoin(r1, ({id}) => id, c, ({id}) => id);
```
