### ISSUE TITLE
can lodash-joins support ` nameA as nameB` feature like SQL?

### ISSUE THREAD

**Issue by ylyxf** [mtraynham/lodash-joins#16]
right array's same property  name will overwrite left property  name

<pre>
var _ = require('lodash-joins');

var left = [
    { id: 'c', left: 0, name: 'helloA_left' },
    { id: 'c', left: 1, name: 'helloB_left' },
    { id: 'e', left: 2, name: 'helloB_left' },
],

    right = [
        { id: 'a', right: 0 },
        { id: 'b', right: 1 },
        { id: 'c', right: 2 },
        { id: 'c', right: 3 },
        { id: 'd', right: 4 },
        { id: 'f', right: 5 },
        { id: 'g', right: 6 }
    ],
    rightWithConflictName = [
        { id: 'a', right: 0, name: 'worldA_right' },
        { id: 'b', right: 1, name: 'worldB_right' },
        { id: 'c', right: 2, name: 'worldC_right' },
        { id: 'c', right: 3, name: 'worldD_right' },
        { id: 'd', right: 4, name: 'worldE_right' },
        { id: 'f', right: 5, name: 'worldF_right' },
        { id: 'g', right: 6, name: 'worldG_right' }
    ],
    accessor = function (obj) {
        return obj['id'];
    };

var a = _.hashInnerJoin(left, accessor, right, accessor);

console.log(a);

var b = _.hashInnerJoin(left, accessor, rightWithConflictName, accessor);

console.log(b);
</pre>

this code will out put like this 

<pre>
[
  { id: 'c', left: 0, name: 'helloA_left', right: 2 },
  { id: 'c', left: 1, name: 'helloB_left', right: 2 },
  { id: 'c', left: 0, name: 'helloA_left', right: 3 },
  { id: 'c', left: 1, name: 'helloB_left', right: 3 }
]
[
  { id: 'c', left: 0, name: 'worldC_right', right: 2 },
  { id: 'c', left: 1, name: 'worldC_right', right: 2 },
  { id: 'c', left: 0, name: 'worldD_right', right: 3 },
  { id: 'c', left: 1, name: 'worldD_right', right: 3 }
]
</pre>

can join functions can accept another more parameter 
<pre>
var rename =  {
        left:{
             name:'leftName'
        },
       right:{
             name:'rightName'
        }
}
var b = _.hashInnerJoin(left, accessor, rightWithConflictName, accessor);
</pre>

**Comment by mtraynham** [comment]
Hi @ylyxf, the current stable version `2.0.3` on npm cannot, but you can use the 3 beta version `3.0.0-beta.2`.   There is a 5th additional parameter to each of the join functions called a `merger` function.  For matching keys provided by the accessor functions, the merger will join the left and right rows to produce a new result.  The default merger result is to simply do a dict merge.

As an example:
```js

var b = _.hashInnerJoin(
    left, 
    accessor, 
    rightWithConflictName, 
    accessor,
    ((l, r) => ({left: l, right: r}) // Results are now dictionaries with a "left" key and "right" key
);
```

I've been meaning to release an actual 3.0 sometime soon, just haven't gotten around to it.  But the beta version has been around for quite a while, so it's essentially stable.

For more info on the merger function, see https://github.com/mtraynham/lodash-joins/issues/12#issuecomment-357365760.

**Comment by ylyxf** [comment]
:+1:  great job ! thank you! @mtraynham
