### ISSUE TITLE
3.0 release?

### ISSUE THREAD

**Issue by wwahammy** [mtraynham/lodash-joins#18]
First off, I wanted to say: awesome work @mtraynham! This is a very cool library.

I noticed that you updated the version in the package.json to 3.0.0. Does this mean the 3.0.0 release is finished? And if it is, would you be able to publish a new version? If not, no worries, totally get that you're busy. I just don't want to bring code in from lodash-joins into my project or make my own build if there's going to be a 3.0.0 release soon.

Thanks again for all the amazing work, this is a super cool library!

**Comment by mtraynham** [comment]
Thanks @wwahammy!

Ahh yes, 3.0.0.  I used to be a user of this very own project, but I haven't used it for sometime and only recently dusted it off.  Guess I was just waiting for any reason to release it 😄 .

All that being said, I'll go ahead and push 3.0.0.

**Comment by mtraynham** [comment]
- [X] Tagged release and some notes about the changes, https://github.com/mtraynham/lodash-joins/releases/tag/v3.0.0.
- [X] NPM published, https://www.npmjs.com/package/lodash-joins/v/3.0.0

Looking forward to any feedback you have @wwahammy, definitely let me know if you encounter some issues.  Thanks!
