### ISSUE TITLE
Wrong types in merger function within IOuterJoin interface

### ISSUE THREAD

**Issue by Mephistofeles** [mtraynham/lodash-joins#20]
Function arguments' types are TLeft and TRight, however it is an outer join, so left or right can be undefined.
It should be defined as TLeft | undefined and TRight | undefined.
I've checked the code and it is defined correctly as merger: Merger<LeftRow | undefined, RightRow | undefined, MergeResult> in hashFullOuterJoin.ts, however as I use the library (I use hashFullOuterJoin function), I get the non-nullable types from index.lodash.d.ts file.

**Comment by Mephistofeles** [comment]
I've checked the code and it is defined as merger: Merger<LeftRow | undefined, RightRow | undefined, MergeResult> in hashFullOuterJoin.ts, however as I use the library (I use hashFullOuterJoin function), I get the non-nullable types.

**Comment by mtraynham** [comment]
Hey @Mephistofeles , apologies for being away.  I've added your suggestion with https://github.com/mtraynham/lodash-joins/commit/2684b6e91be047e8410b850ec34a8985cd43ed3c.  Seems left/right outer join mergers were also wrong.  Thanks for pointing this out!
