### ISSUE TITLE
Different outcome for different implementation?

### ISSUE THREAD

**Issue by Sjoerd82** [mtraynham/lodash-joins#24]
I had expected that the outcome of the join would be the same regardless of the implementation (hash, nested loop, sorted merge). However, while doing a `hashLeftOuterJoin()` I did not get a correct left join, while doing a `nestedLoopLeftOuterJoin()` with the same arguments did return a correct left outer join result...?

If the outcome should have been the same I'll compose an example to add to this question, if not, then perhaps an explanation of the differences should be added to the description of this library.

**Comment by mtraynham** [comment]
Hi @Sjoerd82 can you give me an example of the join?  Hypothetically they should have the same results, but there is one case I know that may be different.

Hash-based joins are slightly different than nested/sorted joins in regards to key comparisons.  Hash simply puts things into a associative array, making no assumption about the keys being string coercible.  For example,

```js
Welcome to Node.js v15.6.0.
Type ".help" for more information.
> x = {}
{}

> y = {}
{}

> y[x] = 5
5

> y
{ '[object Object]': 5 }

> z = {'foo': 'bar'}
{ foo: 'bar' }

> y[z]
5
```

While this may seem wrong, this is simply a product of JS and it's associative arrays.  This can be corrected by having an accessor that distinctly identifies the object as a string, 
```
_.hashLeftOuterJoin(left, (item) => item.id)
``` 
or the more interesting case, stringify-ing the entire row, 
```
_.hashLeftOuterJoin(left, (item) => item.id)
```

If this is not the case, it sounds like a bug and am eager to see the particular use-case.

**Comment by Sjoerd82** [comment]
yeah sure thing, I'm going to clean-up my project a bit to make a working test case for the situation...

**Comment by mtraynham** [comment]
👍 Glad it worked out.  Yeah, the way these join algorithms perform loops doesn't always guarantee consistent ordering, specifically because they could be optimized further if that wasn't a requirement.  You can still sort afterwards though.
