### ISSUE TITLE
Does this repo supports cardinality ? 

### ISSUE THREAD

**Issue by KunalBurangi** [mtraynham/lodash-joins#51]
Does this project support cardinality? 
like n:m, 1:n,, 1:1 and so on ?

**Comment by mtraynham** [comment]
Gotcha - completely understand your point.  I don't think this library really solves your problem.  It is simply a utility to perform database-like joins on JavaScript arrays using common algorithms (hash, nested loop, and sorted merge), and merging them into a single array. It's meant to be pretty basic and there's no smart picking of join algorithm.

Can I ask, can you determine cardinality simply by unique the id fields of each?

**Comment by mtraynham** [comment]
Closing, thanks for taking an interest!
