### ISSUE TITLE
Two Accessors

### ISSUE THREAD

**Issue by boadude** [mtraynham/lodash-joins#6]
<code>
accessor = function (obj) {
...       return obj['id'];
...   };
</code>

How i can do for two key for the join?

**Comment by mtraynham** [comment]
Returning an array from the accessor should work.  

```
accessor = function (obj) { return [obj['id'], obj['name']]; }; 
```

The comparisons are done using `x <= y && x >= y` instead of `==` or `===`, because it's coercive using `Object.prototype.valueOf` or `Object.prototype.toString`.

For instance:
```
var x = ['a', 'b'];
var y = ['a', 'c'];
var z = ['a', 'b'];
x === z // false
x <= z && x >= z // true
x <= y && x >= y //false
```

**Comment by boadude** [comment]
Excelent! .. Thanks!
